import { neon } from "@neondatabase/serverless";
import { config } from "dotenv";
import { drizzle } from "drizzle-orm/neon-http";
import { activeTrips, routes } from "./schema";

// Load .env.local (dev) then fall back to parent .env
config({ path: ".env.local", override: false });
config({ path: "../.env", override: false });

async function seed() {
  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl) {
    console.error("DATABASE_URL environment variable is not set.");
    process.exit(1);
  }

  const sql = neon(databaseUrl);
  const db = drizzle(sql);

  console.log("Seeding routes...");

  const seedRoutes = [
    // ── 7 Sep (Mon) — Hotels to MBS: Welcome Reception (5 buses) ──────────
    {
      conferenceDay: "7 Sep (Mon)",
      serviceName: "Hotels → MBS (Welcome Reception)",
      targetArrival: "17:00",
      pickupLocation: "Rendezvous Hotel",
      dropoffLocation: "MBS Convention Centre",
      scheduledDeparture: "16:30",
      scheduledArrival: "16:50",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "7 Sep (Mon)",
      serviceName: "Hotels → MBS (Welcome Reception)",
      targetArrival: "17:00",
      pickupLocation: "Parkroyal Collection Marina Bay",
      dropoffLocation: "MBS Convention Centre",
      scheduledDeparture: "16:30",
      scheduledArrival: "16:50",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "7 Sep (Mon)",
      serviceName: "Hotels → MBS (Welcome Reception)",
      targetArrival: "17:00",
      pickupLocation: "Rendezvous Hotel",
      dropoffLocation: "MBS Convention Centre",
      scheduledDeparture: "16:35",
      scheduledArrival: "16:55",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "7 Sep (Mon)",
      serviceName: "Hotels → MBS (Welcome Reception)",
      targetArrival: "17:00",
      pickupLocation: "Parkroyal Collection Marina Bay",
      dropoffLocation: "MBS Convention Centre",
      scheduledDeparture: "16:35",
      scheduledArrival: "16:55",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "7 Sep (Mon)",
      serviceName: "Hotels → MBS (Welcome Reception)",
      targetArrival: "17:00",
      pickupLocation: "Rendezvous Hotel",
      dropoffLocation: "MBS Convention Centre",
      scheduledDeparture: "16:40",
      scheduledArrival: "17:00",
      defaultCapacity: 40,
    },
    // ── 7 Sep (Mon) — MBS to Hotels: Return (5 buses) ─────────────────────
    {
      conferenceDay: "7 Sep (Mon)",
      serviceName: "MBS → Hotels (Return)",
      targetArrival: "-",
      pickupLocation: "MBS Convention Centre",
      dropoffLocation: "Rendezvous Hotel",
      scheduledDeparture: "21:00",
      scheduledArrival: "21:20",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "7 Sep (Mon)",
      serviceName: "MBS → Hotels (Return)",
      targetArrival: "-",
      pickupLocation: "MBS Convention Centre",
      dropoffLocation: "Parkroyal Collection Marina Bay",
      scheduledDeparture: "21:00",
      scheduledArrival: "21:20",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "7 Sep (Mon)",
      serviceName: "MBS → Hotels (Return)",
      targetArrival: "-",
      pickupLocation: "MBS Convention Centre",
      dropoffLocation: "Rendezvous Hotel",
      scheduledDeparture: "21:05",
      scheduledArrival: "21:25",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "7 Sep (Mon)",
      serviceName: "MBS → Hotels (Return)",
      targetArrival: "-",
      pickupLocation: "MBS Convention Centre",
      dropoffLocation: "Parkroyal Collection Marina Bay",
      scheduledDeparture: "21:05",
      scheduledArrival: "21:25",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "7 Sep (Mon)",
      serviceName: "MBS → Hotels (Return)",
      targetArrival: "-",
      pickupLocation: "MBS Convention Centre",
      dropoffLocation: "Rendezvous Hotel",
      scheduledDeparture: "21:10",
      scheduledArrival: "21:30",
      defaultCapacity: 40,
    },
    // ── 8 Sep (Tue) — Hotels to MBS: Morning (5 buses) ────────────────────
    {
      conferenceDay: "8 Sep (Tue)",
      serviceName: "Hotels → MBS (Morning)",
      targetArrival: "08:45",
      pickupLocation: "Rendezvous Hotel",
      dropoffLocation: "MBS Convention Centre",
      scheduledDeparture: "08:00",
      scheduledArrival: "08:20",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "8 Sep (Tue)",
      serviceName: "Hotels → MBS (Morning)",
      targetArrival: "08:45",
      pickupLocation: "Parkroyal Collection Marina Bay",
      dropoffLocation: "MBS Convention Centre",
      scheduledDeparture: "08:00",
      scheduledArrival: "08:20",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "8 Sep (Tue)",
      serviceName: "Hotels → MBS (Morning)",
      targetArrival: "08:45",
      pickupLocation: "Rendezvous Hotel",
      dropoffLocation: "MBS Convention Centre",
      scheduledDeparture: "08:10",
      scheduledArrival: "08:30",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "8 Sep (Tue)",
      serviceName: "Hotels → MBS (Morning)",
      targetArrival: "08:45",
      pickupLocation: "Parkroyal Collection Marina Bay",
      dropoffLocation: "MBS Convention Centre",
      scheduledDeparture: "08:10",
      scheduledArrival: "08:30",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "8 Sep (Tue)",
      serviceName: "Hotels → MBS (Morning)",
      targetArrival: "08:45",
      pickupLocation: "Rendezvous Hotel",
      dropoffLocation: "MBS Convention Centre",
      scheduledDeparture: "08:15",
      scheduledArrival: "08:35",
      defaultCapacity: 40,
    },
    // ── 8 Sep (Tue) — MBS to Straits Kitchen: Opening Dinner (7 buses) ────
    {
      conferenceDay: "8 Sep (Tue)",
      serviceName: "MBS → Straits Kitchen (Opening Dinner)",
      targetArrival: "18:45",
      pickupLocation: "MBS Convention Centre",
      dropoffLocation: "Straits Kitchen",
      scheduledDeparture: "18:05",
      scheduledArrival: "18:30",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "8 Sep (Tue)",
      serviceName: "MBS → Straits Kitchen (Opening Dinner)",
      targetArrival: "18:45",
      pickupLocation: "MBS Convention Centre",
      dropoffLocation: "Straits Kitchen",
      scheduledDeparture: "18:05",
      scheduledArrival: "18:30",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "8 Sep (Tue)",
      serviceName: "MBS → Straits Kitchen (Opening Dinner)",
      targetArrival: "18:45",
      pickupLocation: "MBS Convention Centre",
      dropoffLocation: "Straits Kitchen",
      scheduledDeparture: "18:10",
      scheduledArrival: "18:35",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "8 Sep (Tue)",
      serviceName: "MBS → Straits Kitchen (Opening Dinner)",
      targetArrival: "18:45",
      pickupLocation: "MBS Convention Centre",
      dropoffLocation: "Straits Kitchen",
      scheduledDeparture: "18:10",
      scheduledArrival: "18:35",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "8 Sep (Tue)",
      serviceName: "MBS → Straits Kitchen (Opening Dinner)",
      targetArrival: "18:45",
      pickupLocation: "MBS Convention Centre",
      dropoffLocation: "Straits Kitchen",
      scheduledDeparture: "18:15",
      scheduledArrival: "18:40",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "8 Sep (Tue)",
      serviceName: "MBS → Straits Kitchen (Opening Dinner)",
      targetArrival: "18:45",
      pickupLocation: "MBS Convention Centre",
      dropoffLocation: "Straits Kitchen",
      scheduledDeparture: "18:15",
      scheduledArrival: "18:40",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "8 Sep (Tue)",
      serviceName: "MBS → Straits Kitchen (Opening Dinner)",
      targetArrival: "18:45",
      pickupLocation: "MBS Convention Centre",
      dropoffLocation: "Straits Kitchen",
      scheduledDeparture: "18:20",
      scheduledArrival: "18:45",
      defaultCapacity: 40,
    },
    // ── 9 Sep (Wed) — Hotels to MBS: Morning (5 buses) ────────────────────
    {
      conferenceDay: "9 Sep (Wed)",
      serviceName: "Hotels → MBS (Morning)",
      targetArrival: "08:45",
      pickupLocation: "Rendezvous Hotel",
      dropoffLocation: "MBS Convention Centre",
      scheduledDeparture: "08:00",
      scheduledArrival: "08:20",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "9 Sep (Wed)",
      serviceName: "Hotels → MBS (Morning)",
      targetArrival: "08:45",
      pickupLocation: "Parkroyal Collection Marina Bay",
      dropoffLocation: "MBS Convention Centre",
      scheduledDeparture: "08:00",
      scheduledArrival: "08:20",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "9 Sep (Wed)",
      serviceName: "Hotels → MBS (Morning)",
      targetArrival: "08:45",
      pickupLocation: "Rendezvous Hotel",
      dropoffLocation: "MBS Convention Centre",
      scheduledDeparture: "08:10",
      scheduledArrival: "08:30",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "9 Sep (Wed)",
      serviceName: "Hotels → MBS (Morning)",
      targetArrival: "08:45",
      pickupLocation: "Parkroyal Collection Marina Bay",
      dropoffLocation: "MBS Convention Centre",
      scheduledDeparture: "08:10",
      scheduledArrival: "08:30",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "9 Sep (Wed)",
      serviceName: "Hotels → MBS (Morning)",
      targetArrival: "08:45",
      pickupLocation: "Rendezvous Hotel",
      dropoffLocation: "MBS Convention Centre",
      scheduledDeparture: "08:15",
      scheduledArrival: "08:35",
      defaultCapacity: 40,
    },
    // ── 9 Sep (Wed) — Night Safari: Social Programme (7 buses, all same service) ──
    {
      conferenceDay: "9 Sep (Wed)",
      serviceName: "Hotels → Night Safari",
      targetArrival: "18:15",
      pickupLocation: "Rendezvous Hotel",
      dropoffLocation: "Night Safari",
      scheduledDeparture: "17:30",
      scheduledArrival: "18:10",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "9 Sep (Wed)",
      serviceName: "Hotels → Night Safari",
      targetArrival: "18:15",
      pickupLocation: "Parkroyal Collection Marina Bay",
      dropoffLocation: "Night Safari",
      scheduledDeparture: "17:30",
      scheduledArrival: "18:10",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "9 Sep (Wed)",
      serviceName: "Hotels → Night Safari",
      targetArrival: "18:15",
      pickupLocation: "Rendezvous Hotel",
      dropoffLocation: "Night Safari",
      scheduledDeparture: "17:35",
      scheduledArrival: "18:15",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "9 Sep (Wed)",
      serviceName: "Hotels → Night Safari",
      targetArrival: "18:15",
      pickupLocation: "Parkroyal Collection Marina Bay",
      dropoffLocation: "Night Safari",
      scheduledDeparture: "17:35",
      scheduledArrival: "18:15",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "9 Sep (Wed)",
      serviceName: "Hotels → Night Safari",
      targetArrival: "18:15",
      pickupLocation: "Rendezvous Hotel",
      dropoffLocation: "Night Safari",
      scheduledDeparture: "17:40",
      scheduledArrival: "18:20",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "9 Sep (Wed)",
      serviceName: "Hotels → Night Safari",
      targetArrival: "18:15",
      pickupLocation: "MBS Convention Centre",
      dropoffLocation: "Night Safari",
      scheduledDeparture: "17:30",
      scheduledArrival: "18:10",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "9 Sep (Wed)",
      serviceName: "Hotels → Night Safari",
      targetArrival: "18:15",
      pickupLocation: "MBS Convention Centre",
      dropoffLocation: "Night Safari",
      scheduledDeparture: "17:35",
      scheduledArrival: "18:15",
      defaultCapacity: 40,
    },
    // ── 9 Sep (Wed) — Night Safari Return (5 buses) ───────────────────────
    {
      conferenceDay: "9 Sep (Wed)",
      serviceName: "Night Safari → Hotels (Return)",
      targetArrival: "-",
      pickupLocation: "Night Safari",
      dropoffLocation: "Rendezvous Hotel",
      scheduledDeparture: "21:30",
      scheduledArrival: "22:15",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "9 Sep (Wed)",
      serviceName: "Night Safari → Hotels (Return)",
      targetArrival: "-",
      pickupLocation: "Night Safari",
      dropoffLocation: "Parkroyal Collection Marina Bay",
      scheduledDeparture: "21:30",
      scheduledArrival: "22:15",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "9 Sep (Wed)",
      serviceName: "Night Safari → Hotels (Return)",
      targetArrival: "-",
      pickupLocation: "Night Safari",
      dropoffLocation: "Rendezvous Hotel",
      scheduledDeparture: "21:45",
      scheduledArrival: "22:30",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "9 Sep (Wed)",
      serviceName: "Night Safari → Hotels (Return)",
      targetArrival: "-",
      pickupLocation: "Night Safari",
      dropoffLocation: "Parkroyal Collection Marina Bay",
      scheduledDeparture: "21:45",
      scheduledArrival: "22:30",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "9 Sep (Wed)",
      serviceName: "Night Safari → Hotels (Return)",
      targetArrival: "-",
      pickupLocation: "Night Safari",
      dropoffLocation: "MBS Convention Centre",
      scheduledDeparture: "22:00",
      scheduledArrival: "22:45",
      defaultCapacity: 40,
    },
    // ── 10 Sep (Thu) — Hotels to MBS: Morning (5 buses) ───────────────────
    {
      conferenceDay: "10 Sep (Thu)",
      serviceName: "Hotels → MBS (Morning)",
      targetArrival: "09:00",
      pickupLocation: "Rendezvous Hotel",
      dropoffLocation: "MBS Convention Centre",
      scheduledDeparture: "08:30",
      scheduledArrival: "08:50",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "10 Sep (Thu)",
      serviceName: "Hotels → MBS (Morning)",
      targetArrival: "09:00",
      pickupLocation: "Parkroyal Collection Marina Bay",
      dropoffLocation: "MBS Convention Centre",
      scheduledDeparture: "08:30",
      scheduledArrival: "08:50",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "10 Sep (Thu)",
      serviceName: "Hotels → MBS (Morning)",
      targetArrival: "09:00",
      pickupLocation: "Rendezvous Hotel",
      dropoffLocation: "MBS Convention Centre",
      scheduledDeparture: "08:40",
      scheduledArrival: "09:00",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "10 Sep (Thu)",
      serviceName: "Hotels → MBS (Morning)",
      targetArrival: "09:00",
      pickupLocation: "Parkroyal Collection Marina Bay",
      dropoffLocation: "MBS Convention Centre",
      scheduledDeparture: "08:40",
      scheduledArrival: "09:00",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "10 Sep (Thu)",
      serviceName: "Hotels → MBS (Morning)",
      targetArrival: "09:00",
      pickupLocation: "Rendezvous Hotel",
      dropoffLocation: "MBS Convention Centre",
      scheduledDeparture: "08:45",
      scheduledArrival: "09:05",
      defaultCapacity: 40,
    },
    // ── 10 Sep (Thu) — MBS to Hotels: SGATAR Night Return (5 buses) ───────
    {
      conferenceDay: "10 Sep (Thu)",
      serviceName: "MBS → Hotels (SGATAR Night Return)",
      targetArrival: "-",
      pickupLocation: "MBS Convention Centre",
      dropoffLocation: "Rendezvous Hotel",
      scheduledDeparture: "23:00",
      scheduledArrival: "23:20",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "10 Sep (Thu)",
      serviceName: "MBS → Hotels (SGATAR Night Return)",
      targetArrival: "-",
      pickupLocation: "MBS Convention Centre",
      dropoffLocation: "Parkroyal Collection Marina Bay",
      scheduledDeparture: "23:00",
      scheduledArrival: "23:20",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "10 Sep (Thu)",
      serviceName: "MBS → Hotels (SGATAR Night Return)",
      targetArrival: "-",
      pickupLocation: "MBS Convention Centre",
      dropoffLocation: "Rendezvous Hotel",
      scheduledDeparture: "23:15",
      scheduledArrival: "23:35",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "10 Sep (Thu)",
      serviceName: "MBS → Hotels (SGATAR Night Return)",
      targetArrival: "-",
      pickupLocation: "MBS Convention Centre",
      dropoffLocation: "Parkroyal Collection Marina Bay",
      scheduledDeparture: "23:15",
      scheduledArrival: "23:35",
      defaultCapacity: 40,
    },
    {
      conferenceDay: "10 Sep (Thu)",
      serviceName: "MBS → Hotels (SGATAR Night Return)",
      targetArrival: "-",
      pickupLocation: "MBS Convention Centre",
      dropoffLocation: "Rendezvous Hotel",
      scheduledDeparture: "23:30",
      scheduledArrival: "23:50",
      defaultCapacity: 40,
    },
  ];

  const insertedRoutes = await db.insert(routes).values(seedRoutes).returning();

  console.log(`Inserted ${insertedRoutes.length} routes.`);

  // One bus per route, numbered sequentially
  const initialTrips = insertedRoutes.map((route, idx) => ({
    routeId: route.id,
    busIdentifier: `BUS-${String(idx + 1).padStart(2, "0")}`,
    maxCapacity: route.defaultCapacity,
    currentPax: 0,
    assignedLoCount: 1,
    status: "scheduled" as const,
    isSos: false,
    isAdhoc: false,
  }));

  const insertedTrips = await db
    .insert(activeTrips)
    .values(initialTrips)
    .returning();

  console.log(`Inserted ${insertedTrips.length} initial active trips.`);
  console.log("Seeding complete.");
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
